### ISSUE TITLE
API数据接入失败

### ISSUE THREAD

**Issue by CarolejaneCosmos** [uxiaohan/HotList-Web#1]
从9/23晚开始无法更新内容，请作者大大检查一下

**Comment by uxiaohan** [comment]
> 从9/23晚开始无法更新内容，请作者大大检查一下

9月23日中午，接口站被攻击导致服务器进入黑洞，9月24日恢复

**Comment by CarolejaneCosmos** [comment]
![Screenshot_20240927_172144_com kiwibrowser browser](https://github.com/user-attachments/assets/bc4f4206-dcc3-4f4e-9481-d29b8f89d8d8)

**Comment by CarolejaneCosmos** [comment]
发现只有手机上有这个问题
